version: "3.8"

services:
  server:
    build: server
    # restart: always
    environment:
      - MODELS_DIR=/models
      - MODEL_FILE=RWKV-4-Pile-1B5-20220929-ctx4096
    volumes:
      - models:/models
    ports:
      - "8080:8080"

  web:
    build: packages/chat-client
    ports:
      - "3000:3000"

volumes:
  models:
